name: E2E

on:
  schedule:
    - cron: '00 15 * * *' # => equals '00 00 * * *' in JST.
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 120
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run E2E
        run: npm run e2e:ci

      - name: Upload video artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/videos
      - name: Upload report artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: report
          path: report

      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Extract result
        shell: bash
        if: always()
        run: |
          echo ::set-env name=E2E_RESULT::$(jq -r '.stats | [ (.passes|tostring), (.tests|tostring) ] | join("/")' report/report.json)

      # slack
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: notice-kuroco_e2e_test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Test Success :rocket:'
          SLACK_COLOR: good
          SLACK_MESSAGE: |
            ${{ env.E2E_RESULT }}
            please check the result at:
            https://diverta.github.io/front_kuroco_dev/report.html
      - name: Slack Notification on Failure
        uses: rtCamp/action-slack-notify@master
        if: failure()
        env:
          SLACK_CHANNEL: notice-kuroco_e2e_test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: 'Test Failure :boom:'
          SLACK_COLOR: danger
          SLACK_MESSAGE: |
            ${{ env.E2E_RESULT }}
            please check the result at:
            https://diverta.github.io/front_kuroco_dev/report.html

  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '1 week'
        # Optional inputs
        # skip-tags: true
        skip-recent: 7